// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_EXAMPLE_KEY_FROM_FIREBASE_CONSOLE',
    appId: '1:EXAMPLE:web:EXAMPLE',
    messagingSenderId: 'EXAMPLE',
    projectId: 'feedstamer-app',
    authDomain: 'feedstamer-app.firebaseapp.com',
    storageBucket: 'feedstamer-app.appspot.com',
    measurementId: 'G-EXAMPLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_EXAMPLE_KEY_FROM_FIREBASE_CONSOLE',
    appId: '1:EXAMPLE:android:EXAMPLE',
    messagingSenderId: 'EXAMPLE',
    projectId: 'feedstamer-app',
    storageBucket: 'feedstamer-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_EXAMPLE_KEY_FROM_FIREBASE_CONSOLE',
    appId: '1:EXAMPLE:ios:EXAMPLE',
    messagingSenderId: 'EXAMPLE',
    projectId: 'feedstamer-app',
    storageBucket: 'feedstamer-app.appspot.com',
    iosClientId: 'EXAMPLE.apps.googleusercontent.com',
    iosBundleId: 'com.feedstamer.feedstamer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_EXAMPLE_KEY_FROM_FIREBASE_CONSOLE',
    appId: '1:EXAMPLE:ios:EXAMPLE',
    messagingSenderId: 'EXAMPLE',
    projectId: 'feedstamer-app',
    storageBucket: 'feedstamer-app.appspot.com',
    iosClientId: 'EXAMPLE.apps.googleusercontent.com',
    iosBundleId: 'com.feedstamer.feedstamer',
  );
}